language: php

addons:
    chrome: stable

cache:
    directories:
        - .composer/cache/files
        - .phpunit

env:
    global:
        # needed to avoid some hard to fix deprecations
        - SYMFONY_DEPRECATIONS_HELPER="8"

matrix:
    fast_finish: true
    include:
          # Minimum supported dependencies with the latest and oldest PHP version
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="2"
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="2"

          # Test the latest stable release
        - php: 7.2
        - php: 7.3
        - php: 7.4

          # Latest commit to master
        - php: 7.4
          env: STABILITY="dev"

    allow_failures:
          # Dev-master is allowed to fail.
        - env: STABILITY="dev"

before_install:
    - chromedriver-update 80
    - phpenv config-rm xdebug.ini
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;

install:
    - google-chrome --version
    - composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction
    - ./phpunit install

script:
    - composer validate --strict --no-check-lock
    - ./phpunit -v
